name: Kubescape scanning for misconfigurations
on: [push, pull_request]
jobs:
  kubescape:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Get changed files
      id: changed-files
      uses: tj-actions/changed-files@v14.6
    - uses: suhasgumma/github-action@main
      with:
        files: ${{ steps.changed-files.outputs.all_changed_files }}
        suggestFix: true
    - uses: peter-evans/create-pull-request@v4
      with:
        add-paths: "**.yaml"
        commit-message: Add Security
        title: Auto Fixed by Kubescape.
        base: ${{ github.head_ref }}
        branch: kubescape-auto-fix-${{ github.head_ref || github.ref_name }}
        delete-branch: true
